### ISSUE TITLE
Filter not working on TPT

### ISSUE THREAD

**Issue by DanielGrandis** [jcachat/EntityFramework.DynamicFilters#76]
Hi,
I'm try to use your awesome EF filtering model. All features seems good in every case, but I still not get it working in a particular case. I've an abstract Person class, that implement the field for Tenant filtering and a Customer and Supplier classes, inherited from Person, that I want to be filtered (separately) by the current user Id. The field are in the table related to the abstract base class, but I've applied the filters on concrete Customer and Supplier models.

I've implemented filters on model builder like this (Cliente is Customer and Fornitore is Supplier):

``modelBuilder.Filter("CustomersMultiTenancy",
                (Cliente cli, int tenantId, bool isMultiSocieta) =>
                    (cli.SocietaProprietariaId == tenantId) || (cli.IsMultiSocieta == isMultiSocieta),
                () => KAnMoUser.Current.SocietaId,
                () => true);
`
           `modelBuilder.Filter("SuppliersMultiTenancy",
                (Fornitore forn, int tenantId, bool isMultiSocieta) =>
                    (forn.SocietaProprietariaId == tenantId) || (forn.IsMultiSocieta == isMultiSocieta),
                () => KAnMoUser.Current.SocietaId,
                () => true);`
`
I've use SQL Profiler to check the generated SQL query but, in that cases, filter are not applied on the generated SQL. 

Where I'm wrong? 
Same filter application method, but on class Category (not inerited from abstract base, all field in the same table) and the dynamic filter work properly. I'm wondering from this morning on this without finding a solution! 

I hope in your help!

Daniel

**Comment by jcachat** [comment]
Please post the relevant models and also the query you are executing and I will take a look.

**Comment by DanielGrandis** [comment]
Hi, thanks for your reply. Now, after a lot of trouble, seems I've found the correct configuration and filters working (just about 10 minute after my post to you).

Just few questions: is correct to set filters configuration on OnModelCreating event? In this way, I can see that if I change something the add-migration command propagate changes to the database. While, on DbContext creation I must enable or disable filters due to environment global config or user specific configuration parameters, right?

Thanks for your support and very compliments for this awesome improvment to Entity Framework!

Daniel

**Comment by jcachat** [comment]
OnModelCreating is the only place where you can define your filters because we need the DbModelBuilder to do so.

You can enable or disable filters any time you want once they have been created.  If you want to do that inside the DbContext constructor, just be aware that the first time the app launches, they have not been defined until after OnModelCreating has finished (which requires a DbContext instance to be constructed).

**Comment by jcachat** [comment]
Another option for you instead of doing this in the constructor, is to use this functionality:
```
modelBuilder.EnableFilter("UserOrg", (MyContext ctx) => !ctx.UserIsAdmin);
```
See: https://github.com/jcachat/EntityFramework.DynamicFilters#conditionally-enabling-filters

**Comment by DanielGrandis** [comment]
Ok, It's all very straightforward! Just a last question: if I've a "filtered tenant entity" and I'm loding a collection of another entity, **not filtered** with Dynamic Filters, if I use the Include method like 

`Include(f => f.FilteredNavigationProperty)`

the resulting collection of **not filtered** entities is automatically filtered by the filter applied on the navigation property? In other word, is this query expression parsed as an **Inner Join** from entity A to (filtered)entity B where Entity B satisfy filters condition? 

If this working by this way would be really very interesting!

Thanks so much!
Daniel

**Comment by jcachat** [comment]
The filters do not affect how EF creates the joins.  It just adds conditions that will affect the rows returned.  So it's difficult for me to answer your question without seeing specifics.  I would recommend you try it and look at the query to see exactly how it's filtered.

**Comment by DanielGrandis** [comment]
Hi jcachat, I've try any possible configuration, but no way, I'm trying from about 1 hour:

this line of code:
` return Repository.Entities.Include(f => f.Fornitore).ToList();`

throw this Exception:

Eccezione first-chance di tipo 'System.Data.Entity.Core.EntityCommandCompilationException' in EntityFramework.SqlServer.dll

Inner exception say: 
{"Il valore non può essere null.\r\nNome parametro: targetSet"}
(value cannot be null. Parameter name: targetSet}.

This happen only if I apply Dinamic Filters on Type Fornitore (inherited from Anagrafica).

Have you some suggestion on this problem? If I remove Include statmement, all work fine; if I leave the Include but remove che Dynamic Filter on type Fornitore, also, it work fine. 

No way to get it working alltogheter! This is what I'm try to obtain on my previous question. But, SQL not being generated, so I can't provide you a feedback on how Dynamic Filters perform in such situation.

Any suggestion?
Thanks a lot again!

**Comment by jcachat** [comment]
I don't think that issue has anything to do with this one.  More likely, #74 is the same issue.  The exception you're getting seems to be the same.

I would need you to post your models and filters so I can try to reproduce the exception.

**Comment by DanielGrandis** [comment]
Hi, Thanks,

so, thats are the filters:

`
modelBuilder.Filter("WarehouseMultiTanancy",
                (Magazzino mag, int tenantId, bool isMultiSocieta) =>
                    (mag.SocietaProprietariaId == tenantId) || (mag.IsMultiSocieta == isMultiSocieta),
                () => KAnMoUser.Current.SocietaId,
                () => true);

            modelBuilder.Filter("AnagraficheMultiTenancy",
                (Anagrafica an, int tenantId, bool isMultiSocieta) =>
                    (an.SocietaProprietariaId == tenantId) || (an.IsMultiSocieta == isMultiSocieta),
                () => KAnMoUser.Current.SocietaId,
                () => true);

            modelBuilder.Filter("CustomersMultiTenancy",
                (Cliente cli, int tenantId, bool isMultiSocieta) =>
                    (cli.SocietaProprietariaId == tenantId) || (cli.IsMultiSocieta == isMultiSocieta),
                () => KAnMoUser.Current.SocietaId,
                () => true);

            modelBuilder.Filter("SuppliersMultiTenancy",
                (Fornitore forn, int tenantId, bool isMultiSocieta) =>
                    (forn.SocietaProprietariaId == tenantId) || (forn.IsMultiSocieta == isMultiSocieta),
                () => KAnMoUser.Current.SocietaId,
                () => true);

            modelBuilder.Filter("ProductsMultiTenancy",
                (Prodotto ben, int tenantId, bool isMultiSocieta) =>
                    (ben.SocietaProprietariaId == tenantId),
                () => KAnMoUser.Current.SocietaId,
                () => true);

            modelBuilder.Filter("ServicesMultiTenancy",
                (Servizio ben, int tenantId, bool isMultiSocieta) =>
                    (ben.SocietaProprietariaId == tenantId),
                () => KAnMoUser.Current.SocietaId,
                () => true);

            modelBuilder.Filter("CategoriesMultiTenancy",
                (Categoria cat, int tenantId, bool isMultiSocieta) =>
                    (cat.SocietaProprietariaId == tenantId) || (cat.IsMultiSocieta == isMultiSocieta),
                () => KAnMoUser.Current.SocietaId,
                () => true);   
`

the model of Fornitore (Supplier) is:

`
[Table("Fornitori")]
    [SecureName(KAnMoClaimTypes.Fornitore)]
    public class Fornitore : Anagrafica
    {                
        #region 'ctor
        internal Fornitore() : base() {
            _typeCode = "FOR";
        }        
        #endregion      

        #region Properties
        public virtual ICollection<Listino> Listini { get; protected set; }
        public virtual ICollection<RicevimentoMerci> RicevimentiMerce { get; protected set; }
        public virtual ICollection<FatturaFornitore> Acquisti { get; protected set; }   
   
        #endregion
   
        #region Factory Methods 
        
        public static Fornitore Crea(string ragioneSociale, string codice = "")
        {
            Fornitore f = new Fornitore();
            f.RagioneSociale = ragioneSociale;
            f.Codice = codice;

            return f;
        }             
        #endregion
    
    }
`
It's inherit from Anagrafica:

`
 [SoftDelete("IsDelete")]    
    [Table("Anagrafiche")]
    public abstract class Anagrafica : BaseEntity<int>, ITenantAware
    {
        protected string _typeCode = "ANAG";

        #region ITenantAware        
        //[ForeignKey("SocietaProprietaria")]
        [Index("IX_AnagCodeUniqueness", 1, IsUnique = true)]
        public int SocietaProprietariaId
        {
            get;
            set;
        }

        [Required(AllowEmptyStrings=false)]
        [Index("IX_AnagCodeUniqueness", 2, IsUnique = true)]
        [MaxLength(3)]
        public string TypeCode { get { return _typeCode; } protected set { _typeCode = value; } }

        //[ForeignKey("SocietaProprietariaId")]
        //public virtual Societa SocietaProprietaria
        //{
        //    get;
        //    set;
        //}
        #endregion    

        #region fields 
        
        /// <summary>
        /// Codice Anagrafica
        /// </summary>
        private string _codice;

        /// <summary>
        /// Definisce l'insieme dei reparti che hanno visibilità 
        /// sul record, all'interno della Società.
        /// </summary>        
        private IList<RepartoInSocieta> _repartiSocieta;
        /// <summary>
        /// Definisce se attivare la visibilità del record
        /// intrasocietaria. In tal caso, viene ignorata
        /// la funzionalità dei reparti.
        /// </summary>
        private bool _isMultiSocieta;        

        private IList<AttributoAnagrafica> _attributi;        
        #endregion
       
        #region ctor
        protected Anagrafica()
        {
            if (DateTime.MinValue == this.CreatedDateUtc)
            {
                this.CreatedDateUtc = DateTime.UtcNow;
                try
                {                    
                    this.SocietaProprietariaId = KAnMoUser.Current.SocietaId;                    
                }
                catch {
                    //Rollback in caso di creazione anagrafica da update-database (PMC)
                    this.SocietaProprietariaId = 1; 
                }
            }                
        }
        #endregion

        #region Proprieta

        [Index("IX_AnagCodeUniqueness", 3, IsUnique = true)]
        [MaxLength(20)]
        [Required(AllowEmptyStrings=false)]
        public string Codice { get { return _codice; } protected set { _codice = value; } }        
                      
        [Required]
        public string RagioneSociale { get; set; }
        public string PartitaIva { get; protected set; }
        public string CodiceFiscale { get; protected set; }

        #region Proprietà del record e visibilità intrasocietaria
        /// <summary>
        /// Definisce l'insieme dei reparti che possono
        /// vedere il record.
        /// </summary>        
        public virtual IList<RepartoInSocieta> Reparti
        {
            get { return _repartiSocieta; }
            protected set { _repartiSocieta = value; }
        }    
        public bool IsMultiSocieta
        {
            get { return _isMultiSocieta; }
            protected set { _isMultiSocieta = value; }
        }

        public virtual ICollection<RuoloInAnagrafica> Contatti
        {
            get;
            protected set;
        }

        public virtual ICollection<IndirizzoInAnagrafica> Indirizzi
        {
            get;
            protected set;
        }   
        #endregion       

        #endregion

        #region Methods
        /// <summary>
        /// Metodo di assegnazione della partita iva.
        /// Il componente è responsabile della verifica
        /// dei duplicati a DB prima di procedere.
        /// </summary>
        /// <param name="pIva"></param>
        public void ImpostaPartivaIva(string pIva)
        {
            this.PartitaIva = pIva;
        }
        #endregion

        #region Attributi estesi
        public virtual IList<AttributoAnagrafica> AttributiAnagrafica
        {
            get
            {
                if (_attributi == null)
                    _attributi = new List<AttributoAnagrafica>();

                return _attributi;
            }
            protected set
            {
                _attributi = value;
            }
        }

        #region Gestione Attributi

        public AttributoAnagrafica CreaAttributoEsteso(Attributo attributo, string valore)
        {
            var result = AttributoAnagrafica.Crea(this, attributo, valore);
            AttributiAnagrafica.Add(result);
            return result;
        }  

        #endregion

       
        #endregion

        #region SoftDelete
        public bool IsDelete { get; set; }
        #endregion

    }
`

BeneAListino model is a ManyToMany relation between a Product and a Catalog of Supplier:

`
public class BeneAListino : BaseEntity<int>
    {
        public int BeneId { get; protected set; }
        [ForeignKey("BeneId")]
        [Required]
        public Bene Bene { get; protected set; }

        public int ListinoId { get; protected set; }
        [ForeignKey("ListinoId")]
        [Required]
        public Listino Listino { get; protected set; }

        public string CodiceFornitore { get; protected set; }

        /// <summary>
        /// Indica il prezzo di ultimo aquisto per il bene 
        /// in un determinato listino fornitore.
        /// </summary>
        public decimal PrezzoUltimoAcquisto { get; protected set; }

        public int QuantitaMinimaRiordino { get; protected set; }

    }
`

this is a small part of the model, I hope is enought for you to try to reproduce the error.

Thank so much!

**Comment by jcachat** [comment]
Wow, there's a lot there.  Any chance you could reduce this to just the minimum required to reproduce the problem?  I'm happy to help and would like to figure this out but I'm extremely busy right now.  That would save a lot of time.

I already have a unit test with a filter on an included child collection.  So at the moment, I'm not sure what is different in how you are doing it.

**Comment by DanielGrandis** [comment]
Hi, 

 

thank you for your reply. Today I try to clone your repo and debug with source code, so (may be) I can see the source of exception and it’s causes, and try to resolve.

 

If I fix something on the library, I will send you a merge request of some updates.

 

Best regards.

 

 

Daniel Grandis




 

Grandisoft di Daniel Grandis

Consulenza  nel settore delle tecnologie dell’informatica

Via Ugo Foscolo, 17 – 22076 – Mozzate (CO) – Italia
Tel. +39 0331 363271 - +39 348 8093058 – Web:  <http://www.grandisoft.com> www.grandisoft.com
Mail:  <mailto:d.grandis@grandisoft.com> d.grandis@grandisoft.com – Skype danielgrandis1981
P. IVA 03069870123
 <https://www.facebook.com/GRANDISOFT/>  <https://www.linkedin.com/profile/preview?locale=it_IT&trk=prof-0-sb-preview-primary-button> 

 

 

Le informazioni contenute da questo messaggio email sono di proprietà di GRANDISOFT di Daniel Grandis ed hanno carattere confidenziale in quanto rivolte esclusivamente ai destinatari indicati. Ogni diffusione a parti terze o riproduzione, anche se parziale, è espressamente vietata. Ogni uso non autorizzato delle informazioni contenute in questo messaggio e nei suoi allegati, costituisce una esplicita violazione dei diritti di autore e sarà perseguito secondo i vigenti termini di legge. Se avete ricevuto questo messaggio per errore, siete pregati di informare tempestivamente il mittente, segnalando l’errata ricezione e di distruggere quanto avete ricevuto.




 

Da: jcachat [mailto:notifications@github.com] 
Inviato: venerdì 12 agosto 2016 03.40
A: jcachat/EntityFramework.DynamicFilters <EntityFramework.DynamicFilters@noreply.github.com>
Cc: Daniel <d.grandis@grandisoft.com>; Author <author@noreply.github.com>
Oggetto: Re: [jcachat/EntityFramework.DynamicFilters] Filter not working on TPT (#76)

 

Wow, there's a lot there. Any chance you could reduce this to just the minimum required to reproduce the problem? I'm happy to help and would like to figure this out but I'm extremely busy right now. That would save a lot of time.

I already have a unit test with a filter on an included child collection. So at the moment, I'm not sure what is different in how you are doing it.

**Comment by DanielGrandis** [comment]
Hi jcachat,
I've cloned your repository and debugged source code. Exception was thrown at the line

` var entitySet = containers.EntitySets.FirstOrDefault(e => e.ElementType.Name == baseResult.ResultType.EdmType.Name);`

of DynamicQueryVisitorCSpace.cs. The problem seems to be that EntitySets not contain the EntitySet of Fornitore. Fornitore is a derived type from Anagrafica. In my DbContext, I've correctly defined a DbSet<Fornitore> Fornitori {get; set;} but I can't see it into containers.EntitySets collection.

Have you some idea about that?

Thanks in advance!
Daniel

**Comment by DanielGrandis** [comment]
Hi, 
after some other attempt, I found the source of the problem (not the solution yet!).
your `containers` property (the db context) not contain an EntitySet for the derived entity types. So, there is an EntitySet of Anagrafiche, but not an EntitySet of Fornitori. I think this is due to the fact of inheritance strategy. I adopted TPT, so I've a Table for abstract Anagrafica entity type, and a Table for derived Fornitore (supplier) entity type. May be I need to remove filter from derived type do the trick? This is not very comfortable because I want to enable my users to choose the behavior of shared resource (customers and suppliers into the software). By installation configuration parameter, the software could be allow to share customers between multiple company but not supplier, or viceversa, or booth or no one! In this manner, I can only decide to share booth customer and supplier all togheter. And, finally, I'm also not sure that if I remove the filters from customers and suppliers (Cliente and Fornitore) and put them just on Anagrafica (base common type) this can resolve the query visitor issue. What you think about that?

Thanks in advance.
Daniel

**Comment by DanielGrandis** [comment]
This is the cause of the problem: 
https://msdn.microsoft.com/en-us/library/ee382828(v=vs.110).aspx

**Comment by jcachat** [comment]
I had forgotten you were using TPT.  With that in mind, I was able to reproduce the exception.

I was working on this when I saw you posted that link above.  At first I thought that was definitely the problem because your PK is in Anagrafica and even though Fornitore exists in the database as it's own table, it uses that same ID as it's PK and is then FK'd back to Anagrafica.  So it would seem like it's not  a valid relationship in the database to have a table reference Fornitore since the PK is actually owned by Anagrafica.  But, the relationships are created in the database correctly so I'm not entirely sure that link applies to this situation.

I think the real problem is that in version 2, I switched from using SSpace to CSpace to allow filters on navigation properties.  But now, as you have noticed, the derived entity sets are not available when I'm trying to navigate a property reference.  If I switch back to using SSpace, it works correctly and applies the filter to the included child property.

I will need to try to figure out what can be done about that.  At the moment, I don't have a solution.

But, I was able to work around the problem by changing the relationships.  I think the changes you would need to make would be like this:
```
public class Listino : BaseEntity
{
    public int AnagraficaId { get; protected set; }
    [ForeignKey("AnagraficaId")]
    [Required]
    public virtual Anagrafica Anagrafica { get; protected set; }

    public Fornitore Fornitore { get { return Anagrafica as Fornitore; }  }

    public int? ClienteId { get; protected set; }
    [ForeignKey("ClienteId")]
    public virtual Cliente Cliente { get; protected set; }
    public virtual ICollection<BeneAListino> Beni { get; protected set; }

    public string Nome { get; protected set; }
    public decimal ScontoApplicato { get; protected set; }
}
```
And then remove the filter on Fornitore.  That's a duplicate of the filter on Anagrafica anyway.

That should join (at the database level) to the base table (Anagrafica) and still expose a Fornitore property to you (which will be null if it's the wrong type).  Then the filter on Anagrafica can be applied when we are navigating the included property.  But you would also need to .Include(e => e.Anagrafica) instead of Fornitore.

If it's possible for you to do that, it should solve your problem.  At least until I can try to figure out some way to handle it in the library.

**Comment by DanielGrandis** [comment]
Hi jcachat,
the example that you write here is exact what I've tryed this morning and, correctly, it works. But, there some cons on this pattern that I don't like. Firstable, it's hungry from a DDD point of view, have a property twice in my model; second, by putting the filter directly on the Anagrafica entity, I completely lose the possibility of filter Supplier (Fornitore) or Customer (Cliente) one by one. 

What happen in this way, furthermore, is that querying for Listino including Fornitore, anyway, I get all the Listino a DB on wich, Listino of Fornitore not accessible for current user give back the navigation property Fornitore set to null (so, anyway, still need to put a where clausole for filtering not null Fornitore, as available Listino for the user).

So, by now, I use this statment on Listino Service, to query all the Listino available for the user:

`  return Repository.Entities.Include(f => f.Fornitore)
                    .Where(x => x.Fornitore != null && 
                        (x.Fornitore.SocietaProprietariaId.Equals(KAnMoUser.Current.SocietaId) || 
                        x.Fornitore.IsMultiSocieta)).ToList();  `

but, for get this work, I've cloned your repo and put this on line 128 of DynamicFilterQueryVisitorCSpace.cs:

`if (entitySet == null)
                            return baseResult;`

If possible, please fix this for avoid throwing exception by the DynamicFilter in such cases. In this way, if there is problem, simply the filters was not applied at all. I think this is better then now.

Finishing, what do you mean with the statment:
**If I switch back to using SSpace, it works correctly and applies the filter to the included child property.**??? If I install an older version of DynamicFilters can I have this particular case working?

Thanks as usually!

**Comment by jcachat** [comment]
Yes, it's not ideal - hopefully just a temporary workaround until a better solution is found.

If you want Listino to be filtered such that those records are not returned if the Fornitore/Anagrafica filter conditions are true, then you need to create your filter on Listino - not on Fornitore/Anagrafica.  Like this:
```
modelBuilder.Filter("ListinoFilter",
            (Listino l, int tenantId, bool isMultiSocieta) =>
                (l. Anagrafica.SocietaProprietariaId == tenantId) || (l. Anagrafica.IsMultiSocieta == isMultiSocieta),
            () => KAnMoUser.Current.SocietaId,
            () => true);
```

If you filter on Anagrafica, then the filter will exclude those records (set those properties to null) if EF creates an outer join.  I think that is what you are describing so the filter above should do what you want.

You can try downgrading to the last pre-v2 version of the package to see if it works for you.  But the filter I show above is not possible as it requires the changes in v2 to be able to filter on navigation properties.

**Comment by gpcaretti** [comment]
EntityFramework.DynamicFilters 2.3.0
The issue is still there.

Two classes in the model:
```
    public class Owner : User {
        public long? SolicitorId { get; set; }
        [ForeignKey("SolicitorId")]
        public virtual Solicitor Solicitor { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        ...
    }

    public class Solicitor: User {
        ...
    }`
```
If I try execute a query on Owners by including Solicitors:

```
var v1 = Context.Users.OfType<Owner>().ToList();  // ok
var v2 = Context.Users.OfType<Owner>().Include(u => u.Roles).ToList();  // ok
var v2 = Context.Users.OfType<Owner>().Include(u => u.Solicitor).ToList(); // throw ex!
```
Exception message:
System.ArgumentNullException : Value cannot be null. Parameter name: targetSet

Note:
All works with dynamic filter 1.x.y

Stacktrace:

Test Name:	GPSoftware.MyNewHouse.Tests.Users.UserAppService_Tests.GetUsersFull_Test
Test FullName:	GPSoftware.MyNewHouse.Tests.Users.UserAppService_Tests.GetUsersFull_Test
Test Source:	C:\WA\GpES\MyNewHouse.v013\Tests\GPSoftware.MyNewHouse.Tests\Users\UserAppService_Tests.cs : line 162
Test Outcome:	Failed
Test Duration:	0:05:32,247

Result StackTrace:	
at GPSoftware.MyNewHouse.MyNewHouseAppServiceBase.CheckErrorsAndThrowEx(Exception ex, String additionalInfo) in C:\WA\GpES\MyNewHouse.v013\GPSoftware.MyNewHouse.Application\MyNewHouseAppServiceBase.cs:line 92
   at GPSoftware.MyNewHouse.Users.UserAppService.<GetUsersFull>d__12.MoveNext() in C:\WA\GpES\MyNewHouse.v013\GPSoftware.MyNewHouse.Application\Users\UserAppService.cs:line 245
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Abp.Threading.InternalAsyncHelper.<AwaitTaskWithPostActionAndFinallyAndGetResult>d__5`1.MoveNext() in D:\Halil\GitHub\aspnetboilerplate\src\Abp\Threading\InternalAsyncHelper.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Abp.Threading.InternalAsyncHelper.<AwaitTaskWithFinallyAndGetResult>d__3`1.MoveNext() in D:\Halil\GitHub\aspnetboilerplate\src\Abp\Threading\InternalAsyncHelper.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GPSoftware.MyNewHouse.Tests.Users.UserAppService_Tests.<GetUsersFull_Test>d__8.MoveNext() in C:\WA\GpES\MyNewHouse.v013\Tests\GPSoftware.MyNewHouse.Tests\Users\UserAppService_Tests.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
----- Inner Stack Trace -----
   at GPSoftware.MyNewHouse.EntityFramework.Repositories.UserRepository.<GetFlatUsersFullAsync>d__5.MoveNext() in C:\WA\GpES\MyNewHouse.v013\GPSoftware.MyNewHouse.EntityFramework\EntityFramework\Repositories\UserRepository.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Abp.Threading.InternalAsyncHelper.<AwaitTaskWithPostActionAndFinallyAndGetResult>d__5`1.MoveNext() in D:\Halil\GitHub\aspnetboilerplate\src\Abp\Threading\InternalAsyncHelper.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GPSoftware.MyNewHouse.Users.UserAppService.<GetUsersFull>d__12.MoveNext() in C:\WA\GpES\MyNewHouse.v013\GPSoftware.MyNewHouse.Application\Users\UserAppService.cs:line 235
----- Inner Stack Trace -----
   at System.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)
   at System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder.DbExpressionBuilder.Scan(EntitySetBase targetSet)
   at EntityFramework.DynamicFilters.DynamicFilterQueryVisitorCSpace.Visit(DbPropertyExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbPropertyExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitList[TElement](IList`1 list, Func`2 map)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionList(IList`1 list)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbNewInstanceExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbNewInstanceExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbProjectExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbProjectExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at EntityFramework.DynamicFilters.DynamicFilterInterceptor.TreeCreated(DbCommandTreeInterceptionContext interceptionContext)
   at System.Data.Entity.Infrastructure.Interception.DbCommandTreeDispatcher.<Created>b__0(IDbCommandTreeInterceptor i, DbCommandTreeInterceptionContext c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](TResult result, TInterceptionContext interceptionContext, Action`2 intercept)
   at System.Data.Entity.Infrastructure.Interception.DbCommandTreeDispatcher.Created(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Common.DbProviderServices.CreateCommandDefinition(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.CreateCommandDefinition(ObjectContext context, DbQueryCommandTree tree)
Result Message:	
Abp.UI.UserFriendlyException : An error occurred while preparing the command definition. See the inner exception for details.
---- System.Data.Entity.Core.EntityCommandCompilationException : An error occurred while preparing the command definition. See the inner exception for details.
-------- System.ArgumentNullException : Value cannot be null.
Parameter name: targetSet

**Comment by hikalkan** [comment]
@jcachat what do you think about that? Can that be resolved in a short time or do you know a workaround for the issue of @gpcaretti?

**Comment by Enigma007x** [comment]
We also just upgraded from 1.4.11 to 2.3.0 to support the new aspnetboilerplate 1.0 release and are running into the same problem outlined by @gpcaretti.  Unfortunately, we may need to back out the upgrade until there is a fix or workaround for this issue.

**Comment by jcachat** [comment]
I have not found a solution to this yet.  I can avoid the null exception but that results in the query not applying the dynamic filter to the child property.  That's probably preferable to the exception but I would like to try to make this work properly.  But if I can't come up with a solution soon, I will push out a fix that at least avoids the exception.

**Comment by hikalkan** [comment]
Thank you @jcachat 
Please inform us about that if you find a solution or not. Because, all ABP users indirectly using your library (we love it) and this can be a blocking situation for some of them.
If this is not fixed in a short time, we will consider to downgrade to 1.4.11.
Thanks again for this excellent library.

**Comment by geoffrussel** [comment]
@jcachat Thanks for this awesome library! Also looking to upgrade to 2.3.x but stuck in 1.4.11 until this is resolved.

**Comment by jcachat** [comment]
No luck on a proper fix and will probably not have any more time to spend on it in the sort term.  So I pushed out an update that at least (silently) handles the null exception.  It will just result in the filter not being applied to that child property.

**Comment by jcachat** [comment]
I believe I have finally found a solution to this problem.  Please try the new build just pushed out (v2.6) and let me know if it solves all these problems.

It may still generate an "outer apply" where a "left outer join" would be more efficient.  I have not found a way to make that happen yet.

**Comment by martosource** [comment]
I am still getting the "EntitySet not found for {0} or BaseType {1}" Exception.

In my case I have 3-4 deep inheritance.  

I have tested the following change to DynamicFilterQueryVisitorCSpace.cs replace line 177 with.

```
var currentBaseType = baseResult.ResultType.EdmType.BaseType;

while (entitySet == null && currentBaseType != null)
{
    entitySet = containers.EntitySets.FirstOrDefault(e => e.ElementType.Name == currentBaseType.Name);

    if (entitySet == null)
    {
         currentBaseType = currentBaseType.BaseType;
    }
}
```

**Comment by jcachat** [comment]
Sorry it didn't get done sooner, but (thanks to another user) I just pushed this fix into v2.7 of the NuGet package.  Thank you very much for posting this!
